### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by Sergii03** [malwarepad/cavOS#21]
So, i played around with cavOS for a little bit and found several issues.

1. After starting bash from the kernel shell it messes up.
![Image](https://github.com/user-attachments/assets/db7ac8bf-0bc7-4012-9ced-f2d2289141c7)
- To replicate:
Exit from the bash and in kernel shell start bash.

2. Kernel panic when exiting from kernel shell.
![Image](https://github.com/user-attachments/assets/d16deaf1-85d2-489d-90f3-cebef44c3d0b)
- To replicate:
Exit from the bash and in kernel shell type 'exit'.

3. Page fault when trying to start X11.
![Image](https://github.com/user-attachments/assets/3ac0caec-7fd4-406a-8fe9-3a793e7e5d96)
- To replicate:
Run startx in bash.

**Comment by malwarepad** [comment]
Thanks for going through the effort of testing cavOS, it really means a lot! I’m aware of all of those in one way or another…

1. Yeah it’s an issue with waiting which isn’t quite done properly, that I will work on when I’m done with some xorg adjustments. Easy to fix so no worries there.
2. That’s to be expected. The kernel shell is executed inside of the main kernel context and when that one runs out of stuff to do, the kernel panics. In the future when there is proper os structure (init system, etc) the kernel shell will probably be abolished along with direct access to the main kernel context.
3. Startx is useful when there are multiple users present in the system, which in cavOS is not the case. I did all of my testing using xinit and didn’t care about startx. I suggest you do the same and just directly run `xinit`. In the future I might care enough to fix startx but there isn’t much of a point right now being that everything is root. There’s also extra overhead from using that command btw.

Note that you may get xorg shouting about moving a log file when it has already ran and exited (since I’m too lazy to implement a move syscall, will happen shortly). No worries just run `rm /var/log/*` **inside cavOS (not in a tty/host environment)**

**Comment by Sergii03** [comment]
> Thanks for going through the effort of testing cavOS, it really means a lot! I’m aware of all of those in one way or another…
> 
>     1. Yeah it’s an issue with waiting which isn’t quite done properly, that I will work on when I’m done with some xorg adjustments. Easy to fix so no worries there.
> 
>     2. That’s to be expected. The kernel shell is executed inside of the main kernel context and when that one runs out of stuff to do, the kernel panics. In the future when there is proper os structure (init system, etc) the kernel shell will probably be abolished along with direct access to the main kernel context.
> 
>     3. Startx is useful when there are multiple users present in the system, which in cavOS is not the case. I did all of my testing using xinit and didn’t care about startx. I suggest you do the same and just directly run `xinit`. In the future I might care enough to fix startx but there isn’t much of a point right now being that everything is root. There’s also extra overhead from using that command btw.
> 
> 
> Note that you may get xorg shouting about moving a log file when it has already ran and exited (since I’m too lazy to implement a move syscall, will happen shortly). No worries just run `rm /var/log/*` **inside cavOS (not in a tty/host environment)**

xinit gives the same result. `[isr] Page fault occured at cr2{6fffb502369d} rip{100000033cd8}` and isr::task can't kill it.

**Comment by malwarepad** [comment]
Yeah I am testing cavOS with maybe too much memory and some stuff might've slipped through. Fixed with bc71b08

**Comment by Sergii03** [comment]
Hm, still the same thing.

But i found another page fault when running fastfetch:
![Image](https://github.com/user-attachments/assets/128ad9fd-98a0-42b5-be59-153ed513ef22)
![Image](https://github.com/user-attachments/assets/10207f54-569f-4ec5-abaf-5d41bfbe23b2)

This time isr::task kills it as intended.

**Comment by malwarepad** [comment]
Maybe try again (don't forget to `git pull` before doing `make clean && make disk`). I believe 8a091c5 should have solved this.

**Comment by Sergii03** [comment]
It didn't work

**Comment by malwarepad** [comment]
I cannot recreate this problem at all. It could've been caused by a cancelled/corrupted apk attempt or smth, so I'd say try deleting the cavOS repo, whatever propagated in `~/opt/` by `make tools` and re-trying from the start (git clone, etc).

**Comment by Sergii03** [comment]
BTW, `make tools` failed with 
> aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:21: error: Please use exactly Autoconf 2.69 instead of 2.72.
../config/override.m4:12: _GCC_AUTOCONF_VERSION_CHECK is expanded from...
configure.ac:21: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
automake: error: autoconf failed with exit status: 1
make[1]: *** [Makefile:71: tools] Error 1
make[1]: Leaving directory '/home/ukrcrab/Projects/cavOS/src/kernel'
make: *** [Makefile:71: tools] Error 2

To fix it i did `export PREFIX="$HOME/opt/autotools_gcc"
export PATH="$PREFIX/bin:$PATH"`

**Comment by malwarepad** [comment]
You didn’t clean up ~/opt properly most likely

**Comment by malwarepad** [comment]
This could not be replicated (by me or multiple other people in various distros) and I ultimately blame it on some sort of accidental userland corruption. The bug that I fixed with above commit was independent of this issue. If (after doing a proper cleanup) you still have persistent problems, please reopen the issue!
